favicon: null
name: Enersun
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.8338478363584727
  brandStrength: 0.3147595184855163
  rhythmicContrast: 0.5
  brandColors:
    - '#b1d8f9'
    - '#727b7a'
    - '#292826'
    - '#385b6f'
    - '#fefefe'
  lightness: 0.625
typography_spectrum: 0.48733
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.6471536
analytics:
  twitter: null
  google: null
  facebook: null
