name: Enersun
favicon: null
layout_spectrum: 0.33185
typography_spectrum: 0.524594915099442
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b1d8f9'
    - '#727b7a'
    - '#292826'
    - '#385b6f'
    - '#fefefe'
  brandStrength: 0.3147595184855163
  lightness: 0.625
  saturation: 0.8338478363584727
  rhythmicContrast: 0.5
purpose: []
