name: Enersun
favicon: null
layout_spectrum: 0.3741850177757442
typography_spectrum: 0.524594915099442
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bbdcfb'
    - '#9e9284'
    - '#3b3633'
    - '#1f5d8e'
    - '#fefefe'
  brandStrength: 0.3147595184855163
  lightness: 0.2364919309038669
  saturation: 0.8338478363584727
  rhythmicContrast: 0.32729403069242835
purpose: []
